version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mdb
    ports:
      - "27017:27017"
    command: ["--noauth"]
    volumes:
      - mongodb_data:/data/db

  mysql:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: rdb
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: shopdev_elasticsearch
    environment:
      - node.name=shopdev_elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: shopdev_kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  mongodb_data:
  mysql_data:
  redis_data:
  esdata:
