# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD shopDEV

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Copy .env file
      run: |
        /bin/cp /etc/.env ${{ github.workspace }}/.env

    - name: Install dependencies
      run: npm ci

    - name: Restart Node.js app with systemd
      run: |
        pm2 restart shopdev-backend || pm2 start npm --name shopdev-backend -- run dev
        pm2 save
